/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TeacherDashboardImport } from './routes/teacher.dashboard'
import { Route as StudentDashboardImport } from './routes/student.dashboard'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TeacherDashboardRoute = TeacherDashboardImport.update({
  id: '/teacher/dashboard',
  path: '/teacher/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const StudentDashboardRoute = StudentDashboardImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardImport
      parentRoute: typeof rootRoute
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/teacher/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/student/dashboard' | '/teacher/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/student/dashboard' | '/teacher/dashboard'
  id: '__root__' | '/' | '/student/dashboard' | '/teacher/dashboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/student/dashboard",
        "/teacher/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/student/dashboard": {
      "filePath": "student.dashboard.tsx"
    },
    "/teacher/dashboard": {
      "filePath": "teacher.dashboard.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
